print("="*50)
print()
print("Membuat list dengan menginput 5 Elemen")
print()

list = []
nilai1 = input("Masukan Nilai Elemen Ke-1 : ")
nilai2 = input("Masukan Nilai Elemen Ke-2 : ")
nilai3 = input("Masukan Nilai Elemen Ke-3 : ")
nilai4 = input("Masukan Nilai Elemen Ke-4 : ")
nilai5 = input("Masukan Nilai Elemen Ke-5 : ")
list = [nilai1,nilai2,nilai3,nilai4,nilai5]
print("List yang terbuat")
print(*list,sep= "   ")
print()

print("-"*50)
print()
print("Mengakses nilai dari list yang inputkan")
print()
print("Elemen Ke-3 adalah :" ,list[2])
print("Elemen Ke-2 sampai Ke-4 adalah :", *list[1:4],sep= "   ")
print("Elemen Terakhir adalah :" ,list[-1])
print()

print("="*50)
input("Tekan Enter untuk Melanjutkan. . .")
##############################################################
print("="*50)
print()
print("Mengubah Elemen dari List")
print()
print("Mengubah Nilai dari Elemen Ke-4")
print("Nilai di Elemen List Sekarang")
print(*list,sep= "   ")
print()
list[3] = input("Masukan Nilai Penggati Elemen Ke-4: ")
print()
print("Nilai di dalam list setelah di ganti")
print(*list,sep= "   ")
print()

print("-"*50)
print()
print("Mengubah Nilai dari Elemen Ke-4 sampai Elemen terakhir")